id: DEB46B6FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T08:30:27+00:00'
last_modified: '2022-05-30T06:55:29.742127+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '9604':
      image_group_id: I1PD95887
      title: འཇིག་རྟེན་གསུམ་ལས་རྣམ་པར་རྒྱལ་བ་འཕགས་མ་སྒྲོལ་མ་སྒྲུབ་པའི་ཐབས།
      total_pages: 1712
      order: 42
      base_file: 9604.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
