id: P24A3F520
initial_creation_type: ocr
source_metadata:
  volumes:
    9bcaabbac32d4814bd25d1a7df7f6197:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
